### ISSUE TITLE
Update to latest version of implementation

### ISSUE THREAD

**Issue by addyosmani** [tastejs/next-movies#1]
I noticed a few folks are already sharing this app :) This implementation is from around August and we have quite a few months of refinements made to it that we will still be landing to the repo from the mono-repo we've been working in. 

@anton-karlovskiy could you add the PR for those changes?

**Comment by anton-karlovskiy** [comment]
Hi @addyosmani 
I've created a PR with one big commit for now.
When I get a chance, let me try to move the whole commit history to this repo.
Thank you.

**Comment by addyosmani** [comment]
Thank you, Anton! I've gone ahead and approved + merged the PR. For now I think this at least brings the repo inline with the original source in our upstream monorepo 👍🏻 

There are a few approaches we could take in the future to bring over the full commit history:

https://medium.com/@ayushya/move-directory-from-one-repository-to-another-preserving-git-history-d210fa049d4b
https://mattsch.com/2015/06/19/move-directory-from-one-repository-to-another-preserving-history/
