### ISSUE TITLE
Write a good README.md

### ISSUE THREAD

**Issue by anton-karlovskiy** [tastejs/next-movies#3]
@addyosmani 
I think we should write down a good README.md. :)

**Comment by addyosmani** [comment]
Agreed! Took an initial pass on this https://github.com/tastejs/next-movies/commit/2d1a4db0ef59fe911b268262a40978065e3febf3 although I am sure it can be improved :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 
I guess two packages are missing in `Tech Stack` section now:
- @artsy/fresnel
- @loadable/component

**Comment by addyosmani** [comment]
I see you've added these to the README now. Thank you :) I'm going to go ahead and close this issue, but if there are any other key additions you feel we should make to the README let's file new issues or PRs for them. Cheers!
