### ISSUE TITLE
Move TMDB API Key to process.env.TMDB_API_KEY

### ISSUE THREAD

**Issue by addyosmani** [tastejs/next-movies#4]
@anton-karlovskiy Would you be interested in making this change? KEY and token are currently committed to the repo. I think this is probably the last change we might want to make before tagging a proper release.

**Comment by anton-karlovskiy** [comment]
Hi @addyosmani 
I've done the above.
I think we need to set up those environment variables in the Netlify (deploy) configuration.

**Comment by addyosmani** [comment]
@anton-karlovskiy Thanks, Anton! I've moved the project away from /launch to /next-movies for movies.zaps.dev and setup the environment variables in Netlify to get our builds working again. Thanks for making time out to work on those changes!
